import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProviderWrapper from "./wrapers/ReduxProviderWrapper";
import { ThemeProvider, createTheme } from "@mui/material";
import theme from "./wrapers/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json"/>
      </head>

      <body className={inter.className} style={{overflowY: 'hidden',height: '100%', backgroundColor: 'white'}}>
        <ReduxProviderWrapper >
          <ThemeProvider theme={theme}>
          {children}
          </ThemeProvider>
          
        </ReduxProviderWrapper>
      </body>

    </html>
  );
}
